Spanish updates
mozilla/hubs pull request #3169
Opened 2020-10-14 10:22 UTC by keianhzo

Closes #3161 Spanish updates

2020-10-14 10:23 UTC, keianhzo commented
@elmau can you take a look at this and confirm that everything is ok? :) Gracias!

2020-10-14 20:29 UTC, elmau commented
> 
> 
> @elmau can you take a look at this and confirm that everything is ok? :) Gracias!

I'm checking it right now

2020-10-14 20:47 UTC, elmau commented on src/assets/locales/es.json
> +  "sign-in.prompt": "Inicia sesión para fijar objetos en salas.",
"Inicia sesión para fijar objetos en salas." should be "Inicia sesión para fijar objetos en las salas."

2020-10-14 20:49 UTC, elmau commented on src/assets/locales/es.json
> +  "entry.in-lobby-notice": "Estás mirando esta sala desde la antesala.",
"Estás mirando esta sala desde la antesala." should be "Estás viendo esta sala desde la antesala."

2020-10-14 20:50 UTC, elmau commented on src/assets/locales/es.json
> +  "entry.daydream-via-chrome": "Usando Google Chrome",
"Usando Google Chrome" should be "Google Chrome"

2020-10-14 20:51 UTC, elmau commented on src/assets/locales/es.json
> +  "profile.choose_avatar": "Elegir avatares",
"Elegir avatares" should be "Elegir avatar"

2020-10-14 20:53 UTC, elmau commented on src/assets/locales/es.json
> +  "media-browser.search-placeholder.youtube": "Buscar videos de YouTube…",
the "…" looks different from the other ". . ."

2020-10-14 20:55 UTC, elmau commented on src/assets/locales/es.json
> +  "media-browser.empty.favorites": "No tienes ningún favorito. Haz clic en ⭐ para agregar a tus favoritos.",
"No tienes ningún favorito. Haz clic en ⭐ para agregar a tus favoritos." should be "No tienes ningún favorito. Haz clic en ⭐ para agregarlo a tus favoritos."

2020-10-14 20:56 UTC, elmau commented on src/assets/locales/es.json
> +  "audio.title": "Configuración de sonido",
"Configuración de sonido" should be "Configuración de audio"

2020-10-14 20:58 UTC, elmau commented on src/assets/locales/es.json
> +  "preferences.category_audio": "Sonido",
"Sonido" should be "Audio"

2020-10-14 20:58 UTC, elmau commented on src/assets/locales/es.json
> +  "commands.audiomode": "(experimental) Alternar sonido posicional.",
"(experimental) Alternar sonido posicional." should be "(experimental) Alternar audio posicional."

2020-10-14 20:59 UTC, elmau commented on src/assets/locales/es.json
> +  "preferences.category_touchscreen": "Pantallas táctiles",
"Pantallas táctiles" should be "Pantalla táctil"

2020-10-14 21:01 UTC, elmau commented on src/assets/locales/es.json
> +  "preferences.animateWaypointTransitions": "Animar transición de trayectoria",
"Animar transición de trayectoria" should be "Animar transiciones de puntos de referencia"

2020-10-14 21:04 UTC, elmau commented on src/assets/locales/es.json
> +  "home.subscribe_to_mailing_list": "Suscríbete para actualizaciones",
"Suscríbete para actualizaciones" should be "Suscríbete para recibir actualizaciones"

2020-10-14 21:05 UTC, elmau commented on src/assets/locales/es.json
> +  "tips.desktop.video_share_mode": "Estás haciendo una transmisión. Selecciona nuevamente para dejar de compartir el video.",
"Estás haciendo una transmisión. Selecciona nuevamente para dejar de compartir el video." should be "Estás transmitiendo. Selecciona nuevamente para dejar de compartir el video."

2020-10-14 21:11 UTC, elmau requested changes
I wrote some notes around the file with the corrected text, I don't know how to submit corrections here, so I resorted to that.

2020-10-19 12:34 UTC, keianhzo commented
@elmau Updated, in case you want to take a look and confirm that everything looks correct.

2020-10-27 04:15 UTC, johnshaughnessy approved these changes
I don't speak Spanish well enough to comment on the translations and I trust your judgment. Just leaving this review in case I was blocking you from merging it.

2020-11-05 20:07 UTC, elmau commented
Everything looks good with the changes. 👍 Will this be available soon?

2020-11-13 20:50 UTC, misslivirose approved these changes

2020-11-16 16:08 UTC, merged