portuguese (pt-br) language translation revision
mozilla/hubs pull request #3269
Opened 2020-11-03 06:41 UTC by dprado75

Main changes:
- fixed mistype in locale_config.js file
- "cenário" renamed to "cena" to better support its original meaning.
- "entrar" renamed to "fazer login" as this is the usual expression used in a log in form ("Entrar" was kept as the title).
- a whole text block was missing translation and it is now completed. 
- minor fixes and spell checking.

2020-11-24 03:36 UTC, dprado75 commented
Hi @keianhzo Thanks for reviewing the files. You can reply this or tag me if you need any further information on this pull request. The locale_config.js file fixes a mistype ("Português" is the correct spelling for native speakers) and ads "pt-pt" to address Portuguese from Portugal users.
The pt-bt.json file its already commented on the original request.

2020-12-09 09:55 UTC, keianhzo requested changes
Remember to also do a `node sync_locales.js`from `hubs/src/assets/locales` before pushing.

2020-12-09 09:55 UTC, keianhzo commented on src/assets/locales/locale_config.js
> +  "pt-pt": "pt-br",
He have updated the code to handle the sub-language tags so we don't need this anymore. Rebase from master and keep the current master code when rebasing. Let me know if you have issues with that and I can rebase and create a new PR for this.

2020-12-10 13:04 UTC, keianhzo commented
@dprado75 I've moved this PR to https://github.com/mozilla/hubs/pull/3526 to save you the time of rebasing and updating this branch. Thanks for the contribution!

2020-12-10 13:04 UTC, closed without merging