improve japanese locale.
mozilla/hubs pull request #3422
Opened 2020-11-24 06:32 UTC by hATrayflood

- translate new strings.
- unify `,` to `、`
- unify `部屋` to `ルーム`
- unify `オブジェクトをピン留め` to `オブジェクトを固定`
- keep english brand names.
- remove unnecessary inserted spaces like `\n  \n 続行` to `\n\n続行`
- restore deleted spaces like `Bingで検索|` to `Bingで検索 | `
- fix other unnatual japanese translations.

2020-11-24 10:12 UTC, kn1cht requested changes
Translation texts look mostly natural to me. Thanks for your great work!

2020-11-24 10:12 UTC, kn1cht commented on src/assets/locales/ja.json
> +  "cloud.primary_tagline": "Hubs Cloudは、デスクトップ、モバイル、またはVRヘッドセットからアクセスできるプライベートな\ncollaborative 3Dルーム用のサーバーインフラストラクチャを展開します。",
"collaborative" also should be translated :
「Hubs Cloudは、デスクトップ、モバイル、またはVRヘッドセットからアクセスできるプライベートでコラボレーション可能な3Dルーム用のサーバーインフラストラクチャを展開します。」

2020-11-25 04:18 UTC, hATrayflood commented on src/assets/locales/ja.json
> +  "preferences.onlyShowNametagsInFreeze": "フリーズ中の名前タグのみを表示する",
thanks! updated https://github.com/mozilla/hubs/pull/3422/commits/8843b758493fd953647924fa5c55861165b8c0d7

2020-11-25 04:18 UTC, hATrayflood commented on src/assets/locales/ja.json
> +  "cloud.primary_tagline": "Hubs Cloudは、デスクトップ、モバイル、またはVRヘッドセットからアクセスできるプライベートな\ncollaborative 3Dルーム用のサーバーインフラストラクチャを展開します。",
thanks! updated https://github.com/mozilla/hubs/pull/3422/commits/8843b758493fd953647924fa5c55861165b8c0d7

2020-11-27 15:00 UTC, kn1cht approved these changes

2020-12-21 23:01 UTC, brianpeiris commented
I will go ahead and merge this now. Thank you!

2020-12-21 23:08 UTC, merged