Refactor how components are loaded from GLTFs (fix video-texture-target)
mozilla/hubs pull request #4814
Opened 2021-11-05 03:48 UTC by netpro2k

The latest version of ThreeJS broke node references on material components (used video-texture-target). This was due to a change inside GLTFLoader causing materials to be `.clone()`ed when they were not before (though there were certain cases in the past that would probably also trigger this bug). The implementation for `.clone()` on Material and Objec3D kills references on `userData` since it runs it through JSON.stringify/parse. Because of the timing of when this was happening relative to when we were resolving links on material components, the node reference was getting lost...

We want to run all our logic for resolving components after everything else in the GLTF has loaded, so we avoid issues like this. I took this as an opportunity to start cleaning this code up a bit and get rid of the hack that had ThreeJS putting the component data into `userData` for us. We still want to skip putting it into `userData` at all, but this gets us 1 step closer to that.

2021-11-08 16:51 UTC, keianhzo requested changes
The `video-texture-target` component is not working for me using the hubs blender exporter 0.0.13. 

I'm still going over the new loader code but so far I see that since the introduction of the `__mhc_link_type` both in the `video-texture-target` and the `audio-target`components we are looking for an element inside the linked node but it's not there:

https://github.com/mozilla/hubs/blob/3f2893a4c2ac45d72e841f11d1487b0d86ed7a9c/src/gltf-component-mappings.js#L506

I guess as we are now relaying on the `GLTFHubsComponentsExtension` to resolve references, we don't have a aframe element linked from the node as we are not setting it anywhere?

Looking into the `indexToEntityMap` table fixes the issue:
` srcEl = indexToEntityMap[srcNode.userData.gltfIndex];`
But my understanding is that we want to get rid of that mapping.

Also the background doesn't seem to be rendering, I'm not sure if that was the case before...

I'll provide more insights when I'm done parsing code but I don't want to hold this review longer in case you already know where the problem is.

2021-11-08 17:10 UTC, keianhzo commented
I'm also seeing that the texture is video texture flipped in Y and the avatar head and the background is not rendered.

2021-11-09 13:43 UTC, keianhzo reviewed
LGTM

2021-11-09 13:43 UTC, keianhzo approved these changes

2021-11-09 14:00 UTC, keianhzo commented
Now I understand the process better. The flow that caused the issue was:

1. The new GLTF object is loaded
2. `GLTFHubsComponentsExtension` was called and we resolve the `__mhc_link_type` replacing it with the loader created object instance.
3. Right after that the model is cached and cloned so we end up with a disparity in the instances in the `srcNode` reference in the component and the object in the scene graph:
https://github.com/mozilla/hubs/blob/3f2893a4c2ac45d72e841f11d1487b0d86ed7a9c/src/components/gltf-model-plus.js#L665-L670
4. The `.el` backlink is added to the cloned element
https://github.com/mozilla/hubs/blob/3f2893a4c2ac45d72e841f11d1487b0d86ed7a9c/src/components/gltf-model-plus.js#L198
5. The component is inflated:
https://github.com/mozilla/hubs/blob/3f2893a4c2ac45d72e841f11d1487b0d86ed7a9c/src/components/gltf-model-plus.js#L266

The result is that the `srcNode` object reference when the component is inflated is pointing to the original object that doesn't have the `el` link:
https://github.com/mozilla/hubs/blob/3f2893a4c2ac45d72e841f11d1487b0d86ed7a9c/src/gltf-component-mappings.js#L506

2021-11-09 23:18 UTC, netpro2k commented
> The result is that the `srcNode` object reference when the component is inflated is pointing to the original object that doesn't have the `el` backlink:
> 
> https://github.com/mozilla/hubs/blob/3f2893a4c2ac45d72e841f11d1487b0d86ed7a9c/src/gltf-component-mappings.js#L506

Correct. That is why we need to either update this link as part of cloning (like we do for animations) or just resolve the link later (what I did in this PR). It's a bit ugly that the logic for __mhc_link_type is now split into multiple parts, but I think a general refactor of all this component loading stuff is in order at some point anyway.

2021-11-09 23:18 UTC, merged

2021-11-11 12:05 UTC, SV-AndreiC commented
"I have verified this issue and it's working as intended. The video-texture-target is working and showing the intended captures. 
I used https://hubs.mozilla.com/scenes/Rpt8DJS/outdoor-festival for testing this.
Tested on Windows 10 using Firefox 94.0.1 and Chrome 95 browsers. "