Troika Text node
mozilla/hubs pull request #4855
Opened 2021-11-23 19:44 UTC by jameskane05

This is the Hubs PR for displaying Troika Text nodes as defined in https://github.com/mozilla/Spoke/pull/1195, based on the troika-three-text package. This package supports a wide range of styling options and has the advantage of being able to display 3D text consistently in Spoke (pure three.js) and Hubs (A-Frame), making it a superior choice for content management purposes versus A-Frame’s <a-text> nodes or Mozilla’s hubs-text.js method.

To test:

1. Follow testing directions in the Spoke PR: https://github.com/mozilla/Spoke/pull/1195
2. Pull and checkout troika-text branch of Hubs
3. Run npm ci to install the new package
4. Open the scene and check text settings have transferred and display correctly

2021-12-22 15:09 UTC, keianhzo requested changes
Awesome, thanks again for this. Just a few nits but it looks great.

2021-12-22 15:09 UTC, keianhzo commented on src/components/troika-text.js
> +    console.log("init1");
Can be removed.

2021-12-22 15:09 UTC, keianhzo commented on package-lock.json
> +    "bidi-js": {
I think we only want the troika related packages here. I feel that some things have leaked.

2021-12-22 15:11 UTC, keianhzo requested changes

2021-12-22 15:11 UTC, keianhzo commented on src/components/scene-components.js
> +import "./troika-text";
The linter complaints about the missing extra blank line at the end of this file.

2022-01-12 17:31 UTC, jameskane05 commented
@keianhzo I made the two small edits, but as for the package-lock.json update, I think this is correct. `bidi-js` is a dependency of troika-three-text (https://github.com/protectwise/troika/blob/master/packages/troika-three-text/package.json), so wouldn't it make sense it would appear in the package-lock.json after running `npm install`? Let me know what you think.

2022-01-20 15:22 UTC, jameskane05 commented
`bidi-js` is also present in the Spoke yarn.lock for this PR: https://github.com/mozilla/Spoke/pull/1195/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de

2022-02-02 21:48 UTC, netpro2k commented
Gunna take a stab at seeing if I can merge this with our existing text component so we don't need to maintain 2 different ones...

2022-02-11 01:06 UTC, merged