add no wrap to label and accept theme to tooltip border
mozilla/hubs pull request #4880
Opened 2021-11-30 00:50 UTC by matthewbcool

Resolves #4874

I noticed another visual bug when going in to fix this. Longer labels break containers here so this PR fixes that as well.
 
![join room btn](https://user-images.githubusercontent.com/4493657/143965370-ad396835-bc0a-49cf-a648-2a6c4df3dd95.png)

![smooshed](https://user-images.githubusercontent.com/4493657/143965382-e97fd999-3587-4986-b32c-220e766f5291.png)

with no wrap and border:
![fix](https://user-images.githubusercontent.com/4493657/143965581-2fa62ee8-1423-4d95-a427-232976f6239b.png)

2021-12-06 14:54 UTC, keianhzo requested changes
I see that no wrapping cause overlapping issues in some languages.

<img width="284" alt="Screen Shot 2021-12-06 at 15 51 51" src="https://user-images.githubusercontent.com/837184/144867811-cdbcb4a9-a61a-4663-a7ff-3bc3a15cf969.png">

Not sure if the ideal solution would be to go back to wrapping or update the translations to make them shorter but I guess the easiest short term would be wrapping.

2021-12-06 16:50 UTC, matthewbcool commented
Yes, the UI already is breaking in several places with French and Russian so a more permanent solution across all text would be ideal. I've done a couple of these temporary fixes but there is disagreement about translation quality: https://github.com/mozilla/hubs/pull/4837
https://github.com/mozilla/hubs/pull/4823

2021-12-07 12:19 UTC, keianhzo approved these changes

2021-12-07 12:20 UTC, keianhzo commented
Yeah, that makes sense, I guess it's ok to land this and address that on a more holistic way.

2021-12-15 22:11 UTC, merged