preference defaults
mozilla/hubs pull request #5080
Opened 2022-02-05 04:15 UTC by yakyouk

This PR adds defaults for preferences, centralized in store.js. This makes it easier to update and maintain default values for preferences.
Some default values have been moved to store.js as well.

2022-02-05 04:19 UTC, yakyouk commented on src/hub.js
> +store.update({ preferences: { shouldPromptForRefresh: false } }); // Clear flag that prompts for refresh from preference screen
Preference default for `shouldPromptForRefresh` is `false`, so setting this to `false` here will result in `shouldPromptForRefresh` being stripped from preferences.

2022-03-16 14:18 UTC, keianhzo requested changes
LGTM other than the one comment. We have some defensive code around store defaults so a good follow up to this would be to remove all that code.

For example:
https://github.com/mozilla/hubs/blob/7f1c76159cdca4e1082b5c7d37a3da1ee94b4f7e/src/react-components/ui-root.js#L627

2022-03-16 14:23 UTC, keianhzo commented
@yakyouk Thanks for the contribution! I have a few comment but looks good overall.

2022-03-20 17:08 UTC, yakyouk commented on src/react-components/preferences-screen.js
> +          SCHEMA.definitions.preferences.properties[this.props.storeKey].default;
yes good point, this could be cleaned up by just using `DEFAULT_MAX_RESOLUTION` directly as preference default

2022-03-20 17:11 UTC, yakyouk commented on src/react-components/preferences-screen.js
> +            defaultBool: prefSchema.enableOnScreenJoystickLeft.default
> We have some defensive code around store defaults

Ah right, this is exactly what this PR is trying to solve. Will look this over when I find time

2022-03-21 06:24 UTC, yakyouk commented on src/react-components/preferences-screen.js
> +            defaultBool: prefSchema.enableOnScreenJoystickLeft.default
All the places where defaults were set through logic are now using preferences directly.
- `isFirefoxReality` workaround has been moved to `store.js` and is used as the default for `disableEchoCancellation`, `disableNoiseSuppression` and `disableAutoGainControl`
- max resolution default has been kept `undefined`, the actual default is the current screen resolution

2022-03-22 12:40 UTC, keianhzo requested changes
Hey @yakyouk this looks great.

In my previous comment about the preferences-screen components defaults I was talking about getting rid of all the:
https://github.com/mozilla/hubs/blob/230553ad2de61bd662b4d04f4ec81e01a2582e83/src/react-components/preferences-screen.js#L102-L107
and simplifying it to:
```
      const digits = Math.max(this.state.digitsFromUser, this.props.digits);
      this.setState({ displayValue: this.props.store.state.preferences[this.props.storeKey].toFixed(digits) });
```
As if I understand correctly the preference now will always return either the current value or the default.

I think we can do that for all components and that way we can get rid of all the preferences default definitions like:
https://github.com/mozilla/hubs/blob/230553ad2de61bd662b4d04f4ec81e01a2582e83/src/react-components/preferences-screen.js#L973
https://github.com/mozilla/hubs/blob/230553ad2de61bd662b4d04f4ec81e01a2582e83/src/react-components/preferences-screen.js#L990


Let me know if you have time for this change otherwise I can land this and fix it in an upcoming PR.

2022-03-23 03:47 UTC, yakyouk commented
Right, that makes sense, I didn't notice it could be simplified. I'll try to get that done by the end of the week.

2022-03-23 15:01 UTC, merged