bitECS: Fix Text color problem
mozilla/hubs pull request #6218
Opened 2023-08-15 21:38 UTC by takahirox

Fixes #6216 

**Problem**

With new loader enabled text component color can look weird.

**Root issue**

Text inflator expects some parameters are passsed as number but they can be passed as strings from glTF. Then text can look weird due to mismatched data type.

**Solution**

Add casting in text inflator to ensure data types. Adding casting only number typed parameters that actually caused a problem for now.

**Additional context**

This type check and casting problem shouldn't be text component specific. The real root issue is glTF component data is not type checked and validated.

Ideally all the (glTF) inflator parameters should be type checked and validated. We may need to add type check and validation mechanism later.

2023-08-18 07:18 UTC, keianhzo reviewed
Not sure if I understand the approach. We control both end the authoring tools (Spoke/Blender) and the client code so we should be able to make all parameters match types. If there is some parameter that doesn't, wouldn't it be simpler to just cast that specific parameter instead of adding all this casting logic for the whole params object?

2023-08-18 18:58 UTC, takahirox commented
1. We can't really trust glTF/glb contents coming from external (eg: user upload, from sketchfab). We can't perfectly assume that the assets are exported with Spoke or Hubs Blender addon properly. Even users can manually (and wrongly) edit their contents. So we need validation layer somewhere. Perhaps validating in glTF inflators is one of the good candidates. We may also rescue some invalid data like with casting. Anyways we need to discuss how we should handle invalid data (eg: Refuse, apply default values, or rescue as much as possible).

2. Imaginar shared glb assets including text component exported with Hubs Blender add-on. `outlineBlur, outlineOfffsetX/Y, outlineWidth, strokeWidth` in the assets seems to be exported as strings although they are expected as numbers in Hubs Client. With the old loder, they seems to be converted to numbers in Hubs Client. Perhaps A-Frame has a mechanism to cast component data with A-Frame component schema. For the assets Imaginar shared, refer to Discord "New loader test with the community" subchannel under meetup channel.

![image](https://github.com/mozilla/hubs/assets/7637832/5d20e983-734f-4d7a-bc89-933811e4dcbd)

I guess Hubs Blender add-on has a bug for exporting text? I'm not sure which properties are exported as wrong type. So added casting for all number typed parameters for now.

2023-09-12 10:13 UTC, keianhzo requested changes
Those parameters that you mention (`outlineBlur, outlineOfffsetX/Y, outlineWidth, strokeWidth`) are not only numbers, they can be numbers or strings, both are valid and both are accepted by TroikaText (https://github.com/protectwise/troika/blob/main/packages/troika-three-text/README.md#outlineblur): 
`outlineBlur?: number | `${number}%`;`

In AFrame we were checking this by using a parsing function here:
https://github.com/mozilla/hubs/blob/02ff9d03c384ce6caef14a441945d52f916e2d53/src/components/troika-text.js#L16
and here:
https://github.com/mozilla/hubs/blob/02ff9d03c384ce6caef14a441945d52f916e2d53/src/components/troika-text.js#L40

I suggest we take a similar approach to avoid any breakage and ensure campatiblity.

That would fix the issue and get this to parity with the AFrame code.

The Blender add-on code looks good to me. the property there is exported as a string as we are relying on the Hubs client to determined the correct type based in the "%" symbol presence and cast accordingly.

2023-09-13 01:26 UTC, takahirox commented
``${number}%`` style is covered here.

```
    value = Number(value);
    if (isNaN(value)) {
      continue;
    }
```

`Number('12%') -> NaN`

2023-09-13 08:23 UTC, keianhzo commented
Oh yes, sorry I misunderstood that. We are correctly handling the three cases:
`${number}`
`${number}%`
`number`
Maybe we should reflect that in the type declaration?

2023-09-13 08:24 UTC, keianhzo approved these changes
Oh yes, sorry I misunderstood that. We are correctly handling the three cases. Maybe we should reflect that on the property declaration?
```typescript
outlineBlur?: number | `${number}%` | `${number}`;
```

I like the AFrame approach were you can provide a parsing function for each property but I guess this can work for now.

2023-09-14 00:21 UTC, merged

2023-09-14 02:59 UTC, takahirox commented
> Maybe we should reflect that on the property declaration?
>
> ```
> outlineBlur?: number | `${number}%` | `${number}`;
> ```

In my opinion, valid types and types that can be rescued for glTF should be distinguished. So, for example, `outlineBlur?` types should be kept being

```
number | `${number}%`
```

Static type check where possible (JSX) shouldn't really widen the valid types. And we may change how to handle invalid typed data, for example in this PR we rescue strings number but we may change it to refuse in the future.