update lib-hubs to latest commit in package-lock.json
mozilla/hubs pull request #6419
Opened 2023-12-14 23:31 UTC by kfarr

https://github.com/mozilla/hubs/issues/6418

2023-12-15 09:05 UTC, hrithikwins approved these changes

2023-12-15 21:44 UTC, mikemorran commented
@keianhzo Can we get your eyes on this? I know you spent some time this week debugging this issue

2023-12-19 15:33 UTC, keianhzo requested changes
Thanks for this @kfarr! I think this was the missing piece in the puzzle. Unfortunately, there are a few unrelated changes that prevent us from merging this PR. Can you please clean up the PR and remove all changes except from the package-lock.json line? Thanks!

2023-12-19 20:08 UTC, kfarr commented
@keianhzo yes try this PR instead https://github.com/mozilla/hubs/pull/6425

2023-12-19 20:08 UTC, closed without merging